### ISSUE TITLE
One docker volume for both services

### ISSUE THREAD

**Issue by arv-anshul** [arv-anshul/yt-watch-history#14]
Currently, we are using multiple volumes to sync the data with docker containers but now I want to combine all the volumes in one.

**Current config in `docker-compose.yaml` file:**

```yaml
services:
  frontend:
    volumes:
      - ./frontend:/frontend  # TODO: Learn why are we doing this
      - ./frontend/data:/frontend/data
  backend:
    volumes:
      - ./backend:/backend  # TODO: Learn why are we doing this
      - ./backend/ml_models:/backend/ml_models

volumes:
  frontend:
  data:
  backend:
  ml_models:
```

But I want to combine all the volumes in one with `data/` directory.

```bash
.
├── backend
│   └── ...
├── data  # This directory as universal volume
│   └── ...
└── frontend
    └── ...
```

**😞 Not Sure;** And for this, we have to change following in `docker-compose.yaml` file:

```diff
services:
  frontend:
    volumes:
-      - ./frontend:/frontend
-      - ./frontend/data:/frontend/data
+      - ../data:../data
  backend:
    volumes:
-      - ./backend:/backend
-      - ./backend/ml_models:/backend/ml_models
+      - ../data:../data

volumes:
-  frontend:
  data:  # 🤔 I am not sure this line stays the same or not
-  backend:
-  ml_models:
```

> I am not sure that this works for sure.

Also, you have change path of data files and models.
